### ISSUE TITLE
Distribute windows version as .zip

### ISSUE THREAD

**Issue by youreperfect** [Galleondragon/qb64#102]
Windows has native support for extracting .zip files and .7z requires installation of a special program - this creates a barrier of entry for casual users wanting to check the project out.

**Comment by callowaysutton** [comment]
7z has better compression and is generally more optimized with the added bonus that installing 7-zip adds support for many other compression formats, it doesn't have any downsides besides having to actually install it

**Comment by youreperfect** [comment]
Its a single 80mb file - even if zip is twice the size at 160mb it doens't matter - many users will have never heard of 7zip. Having to install some extra software the user has never heard of and may need only for unzipping this one application is a lot bigger downside than a couple extra mb in download size IMHO. Windows includes support for .zip, I can't see any valid argument against using a natively supported compression format for something this size.

This is especially true when places like: https://github.com/Galleondragon/qb64/releases/tag/v1.3
don't explain it. How many users download it then have no idea what to do with it and give up?

**Comment by FellippeHeitor** [comment]
Considered for next release. Closed as its not code related.
