### ISSUE TITLE
Add built in ASSERT function

### ISSUE THREAD

**Issue by youreperfect** [Galleondragon/qb64#111]
Something like this:

`SUB assert (condition AS _BYTE, message AS STRING)
    IF condition = 0 THEN
        PRINT message
        END
    END IF
END SUB
`

which can be used in creating simple unit tests or sanity-checking in code. Below are two use cases from a little project I started.

preferably the built-in assert would be a little more robust than my simple one.

wish list:
* message parameter should preferably be optional, or make two functions like assert() and assert_msg()
* it should print the line number that called the assert if it fails (ie: FATAL: assert on line 839 in MYPROG.BAS) or similar
* it should only do anything in debug builds or when running in the editor. Release builds should treat assert calls as NOOP, not even evaluating the condition.

Two use cases

1. Ensures the user is using the Matrix type correctly and that internal memory management is correct. 
`
```
FUNCTION matrix_get (matrix AS Matrix, row AS INTEGER, column AS INTEGER)
    assert matrix.Initialized, "Matrix not yet initialized, use matrix_init <matrix>,<rows>,<columns>"
    assert row > 0 AND row <= matrix.Rows, "Row out of bounds"
    assert column > 0 AND column <= matrix.Columns, "Column out of bounds"
    assert row * column < matrix.RawData.SIZE / MATRIX_INT_SIZE, "matrix_get: Internal matrix data error, probably not your fault"
    DIM ret AS INTEGER
    _MEMGET matrix.RawData, matrix.RawData.OFFSET + (row * column * MATRIX_INT_SIZE), ret
    matrix_get = ret
END FUNCTION
````

2. Simple unit tests
`
```
SUB matrix_run_tests
    DIM m AS Matrix

    'pre-initialization
    assert m.Rows = 0, "pre-init: rows != 0"
    assert m.Columns = 0, "pre-init: columns != 0"
    assert m.Initialized = 0, "pre-init: initialized is non-false"
    assert NOT matrix_is_valid(m), "pre-init: matrix should not be valid yet"
    assert matrix_is_zero(m), "pre-init: matrix reporting as non-zero"
    PRINT "Matrix pre-init: PASS"

    'initialization
    matrix_init m, 1, 1
    assert matrix_is_valid(m), "init: 1,1 matrix reporting invalid"
    assert matrix_is_zero(m), "init: 1,1 matrix reporting non-zero"
    assert m.Rows = 1, "init: 1,1 matrix wrong row count"
    assert m.Columns = 1, "init: 1,1 matrix wrong column count"
    matrix_init m, 100, 100
    assert matrix_is_valid(m), "init: 100,100 matrix reporting invalid"
    assert matrix_is_zero(m), "init: 100,100 matrix reporting non-zero"
    assert m.Rows = 100, "init: 100,100 matrix wrong row count"
    assert m.Columns = 100, "init: 100,100 matrix wrong column count"
    PRINT "Matrix init: PASS"

    'destruction
    matrix_free m
    assert NOT matrix_is_valid(m), "free: matrix should not be valid yet"
    assert matrix_is_zero(m), "free: matrix reporting as non-zero"
    PRINT "Matrix destruction: PASS"
````

**Comment by FellippeHeitor** [comment]
sounds like it'd require a _ASSERTS ON at the top and a $CONSOLE window mandatorily created, is that the kind of thing you've envisioned?

**Comment by youreperfect** [comment]
I think there could be 4 approaches that come to mind immediately:
1) always have the console on when doing debug builds (Godot does this)
2) what you mention
3) when an assert happens, show the assert message in a window-manager alert/error box instead of on the console, like when you have unhandled exceptions in Java applications
4) check if there is a console open in the application, if so show it to the console, if not do 3

**Comment by FellippeHeitor** [comment]
If the assert message is to be considered an error, the message box should be more of an expected outcome after all

**Comment by youreperfect** [comment]
Yes a failed assert should always be a fatal error. Oh and it should exit the program with a _CRT_ASSERT (or maybe _CRT_ERROR) error code so the OS interprets it as a program crash and can offer to connect a debugger. 

_CRT_ASSERT I think would normally be the right choice, but for some reason Q_ASSERT in Qt calles qFatal which exits with _CRT_ERROR.

If showing the assert message to the user in a GUI window, it should allow the user a way to copy the assert message so they can more efficiently complain to the script's developer. Perhaps a "Copy error to clipboard" button.

Also there should be a flag to that will supress the gui popup and read STDERR instead on assert, in order to support automated testing that doesn't rely on user interaction. I guess there are a couple ways to do this: a) add an _ASSERT_TO_STDERR ON file-scoped option that could be put at the top of files that are just for automated tests (and defaults to OFF and shows the GUI window on assert) or b) as an optional flag on the compiled application's executable that will direct all asserts to STDERR and not rely on user interaction. Something like myprogram.exe --assert-to-stderr. I think this second option would be slightly better as it wouldn't rely on user's remembering to add the option to the test scripts and automatic testing-controllers would just add this flag to every program it run.s

**Comment by davidshq** [comment]
I'd love to see unit testing available in QB64. FWIW, there is a unit testing library for FreeBasic, not sure how hard it would be to port over... https://github.com/jayrm/fbcunit
