### ISSUE TITLE
sound and licenses of sound

### ISSUE THREAD

**Issue by JazzMaster** [Galleondragon/qb64#19]
call this an rfc- i dunno but...

sdl has sound. If licensing of sdl is gpl then sound libs should also be gpl...therefore the seperate licensing shouldnt be required.

Im working a bgiSDL api for fpc(libgraph)...so I know enough to be dangerous. Initial thinking maybe on similar libs to mplayer's ffmpeg but that also seems gpl not lgpl. I could be wrong. 

Im learning the internals as I go..but it really is "simple" even by complex "bgi standards". And NO, FPC doesnt have a port of this. C has 4.Two work with effort. So my work isnt wasted.

Interesting that you tie it to QB though. 
For those interested, SFML may provide better "game interface"? code... its really heavy on OGL and complex shaders that SDL needs a lot of work to handle.

GOD its been ages....93-94? GEEZ..Im old.
I dont really care for everyone porting to C/CPP but this is a start. C has dodgy pointers...and its a royal u-know-what to debug. Of course w fpc I have to break out the manual to see what the compiler is complaining about....

**Comment by FellippeHeitor** [comment]
In short, what is the issue again?

**Comment by JazzMaster** [comment]
sdl apparently...next time read the text. noticed it w pascal...

**Comment by FellippeHeitor** [comment]
I read the text before I asked you to summarize your issue, read it again now that you said I hadn't, and I still believe you don't have an issue with QB64. If you understand there is an issue with QB64, please provide more details and we may open this issue again.
