### ISSUE TITLE
Allow the enabling / disabling of built-in ALT+ENTER fullscreen toggle

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#22]
Hello there. The fact that QB64 goes through multiple screen-stretching modes when you use ALT+ENTER is a problem for me. A command to set which mode(s) the fullscreen shortcut uses would be good, allowing users to specify things like 'use only stretched & smoothed mode' or to disable the built-in fullscreen switch entirely so that they can trap the keys and handle it how they want (for example, I've added an F11 shortcut to my app to do fullscreen).

**Comment by flukiluke** [comment]
I agree. Any suggestions for a command name?

**Comment by Kroc** [comment]
Something like `_ALLOWFULLSCREEN` and then a set of flags to specify which modes should be available. This could be a metacommand, but I think there's value in allowing a game to change which fullscreen modes are used in different parts of a program -- games, for example.
