### ISSUE TITLE
BUG: SCREEN(function) returning ASCII 219 "█" on SCREEN 12 30-rows, but not on 25-rows

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#23]
I have a strange bug. I'm using SCREEN 12 with 30-rows (640x480). I am trying to read from the screen to be able to draw a shadow around a dialogue box (read the ASCII code, print a black-background version back). 

This is a portion of the code:

```
    'draw the shadow along the bottom
    LET y% = boxTop% + boxHeight% + 2
    FOR x% = (boxLeft% + 1) TO (boxLeft% + boxWidth%)
        LET char% = SCREEN(y%, x%, 0)
        COLOR DKGREY, BLACK
        LOCATE y%, x%
        PRINT CHR$(char%);
    NEXT
```

With `SCREEN 12: WIDTH 80, 30` the `SCREEN(...)` function *always* returns code 219; solid-block, not even space as the documentation says. If I change to 25 rows, it works as expected.

**Comment by Kroc** [comment]
NB: work-around is to use SCREEN 0 with 30 rows -- which wasn't possible (I think) on v1.1; I only found out about the new version today.

**Comment by FellippeHeitor** [comment]
Contrary to what happens in SCREEN 0, when the character information is stored for each coordinate alongside the color used, in graphic modes SCREEN() attempts to identify the character at the specified coordinate by comparing the block to the built-in font. If there's a pixel-by-pixel match, it returns the character found. Now, there is no graphic difference between a space printed with COLOR 0, 7 and a CHR$(219) block printed with COLOR 7, 0, and that's where the function apparently "fails", when it actually did a good job in matching the character it found.
