### ISSUE TITLE
No `_FOREGROUNDCOLOR` even though there is `_BACKGROUNDCOLOR`

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#30]
This is quite important for my use case as I'm writing an ANSI escape sequence interpreter and when the function is called to print an ANSI string, we need to know what the current fore/back-ground colour are to restore to when the clear or reset colour sequence is used.

Of course, we can read the colour from the current cursor position using `_SCREEN()`, but given that the ANSI escapes can move the cursor around and that what's on the screen may not be the 'default' colours that the user intends to fall back to, I need to be able to read the currently set foreground colour without actually writing anything to screen in order to do so. For example, a typical usage scenario would be something like this:

```BAS
LOCATE 15, 5: COLOR 1, 7: ANSI_PRINT some_string$
```

Here, we want to default to colours 1 & 7 when any ANSI escape sequence changes the colour and then resets it -- but there is no guarantee that the cell at 15, 5 is using those colours!

Here's a sample program that shows `_BACKGROUNDCOLOR` in use; we can read a colour without it having to be on screen. I'd like to be able to do the same with the foreground colour.

```BAS
SCREEN 0: COLOR 14, 1: CLS
PRINT
PRINT "The original background is 1"
PRINT
PRINT "But the current background is ";
COLOR , 3
DIM c%: LET c% = _BACKGROUNDCOLOR
COLOR , 1
PRINT c%
```

**Comment by Kroc** [comment]
P.S. In theory I could use `OUT` / `INP` to read the current foreground color from the emulated VGA, but I can't find a concrete way to do exactly this and VGA internals are severely confusing.

**Comment by FellippeHeitor** [comment]
_DEFAULTCOLOR
