### ISSUE TITLE
Linux doesn't apparently sort file list output 

### ISSUE THREAD

**Issue by FellippeHeitor** [Galleondragon/qb64#31]
Reported at http://www.qb64.net/forum/index.php?topic=14715.msg127829#msg127829

**Comment by mkilgore** [comment]
Hey, I think I might know the problem. These few lines in ./source/ide/ide_methods.bas:

```
IF method = 0 THEN
    IF i = 1 THEN SHELL _HIDE "find " + QuotedFilename$(path$) + " -maxdepth 1 -type f -name " + CHR$(34) + "*.bas" + CHR$(34) + " >./internal/temp/files.txt"
    IF i = 2 THEN SHELL _HIDE "find " + QuotedFilename$(path$) + " -maxdepth 1 -type f -name " + CHR$(34) + "*.BAS" + CHR$(34) + " >./internal/temp/files.txt"
END IF
IF method = 1 THEN
    IF i = 1 THEN SHELL _HIDE "find " + QuotedFilename$(path$) + " -maxdepth 1 -type f -name " + CHR$(34) + "*" + CHR$(34) + " >./internal/temp/files.txt"
END IF
```

`find` won't sort its output. That's easy enough to fix by just piping the results to `sort` first, so the lines turn into this:

```
    IF i = 1 THEN SHELL _HIDE "find " + QuotedFilename$(path$) + " -maxdepth 1 -type f -name " + CHR$(34) + "*" + CHR$(34) + " | sort >./internal/temp/files.txt"
```

Unfortunately my QB64 instance is borked at the moment and won't compile so I was unable to test it. I'm also not quite sure if those are the only locations that need the update, or if there are other spots where QB64 `SHELL`s out to `find`.

**Comment by FellippeHeitor** [comment]
I believe that's the sweet spot indeed, @mkilgore, thanks for investigating the issue.
