### ISSUE TITLE
Allow `_DEFINE` to define string prefixes for automatic typing

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#32]
That is, the ability to use:

```
_DEFINE "int" AS _UNSIGNED INTEGER
_DEFINE "lng" AS _UNSIGNED LONG

LET intSmallNumber = 65535
LET lngBigNumber = 2 ^ 31
```

Auto-typing variables (and function!) based on a single letter is a bit risky and I'd prefer the approach common with VB6 (3 letter prefix). It's expected this would be case-sensitive so as to minimize interference with functions, which are typically CamelCased.

**Comment by flukiluke** [comment]
The use of _DEFINE with any range other than A-Z is discouraged.

Thanks to the use of type suffix symbols, Hungarian notation where you're just prefixing the system type is also frowned upon (see Systems vs Apps Hungarian).
