### ISSUE TITLE
`SCREEN 0` blinking colours should continue to blink when using `_DISPLAY`

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#33]
The `_DISPLAY` function is a very nice way to do away with manual double-buffering, but it has one drawback -- blinking colours in `SCREEN 0` do not continue to blink as expected; yes, the blinking is technically refreshing the display, but the benefit of the blinking colours is that they blink automatically and you're not having to update the colours yourself every frame (what a nightmare that would be).

This could be resolved by copying the screen memory to a private buffer and doing the automated blinking from that buffer -- that way, updates to the screen won't automatically appear on screen until `_DISPLAY` is called again.

There doesn't appear to be a simple way to read the blinking state of a character on the screen -- I had to resort to reading screen memory; and because I'm forced to use double-buffering (due to blinking) this also screws with reading screen memory; the screen page number has to be stored in a global variable and I need factor that into the screen address calculations. This is a lot of complication that would not be needed if `SCREEN 0` continued to blink when using `_DISPLAY`.

(nb: a function to read the blink-state of a screen co-ordinate would make life easier; e.g. `blink = SCREEN(y, x, 2)`)

**Comment by FellippeHeitor** [comment]
If your screen is going to remain unrefreshed for long enough to allow blinking, just call _AUTODISPLAY before your program comes to an expected halt. You can also read the _AUTODISPLAY function to know if it's active (-1) or not (0).
