### ISSUE TITLE
Releases page is confusing

### ISSUE THREAD

**Issue by JasonGlazer** [Galleondragon/qb64#37]
Today March 2, the releases page shows that you just released 1.1 but on that same page shows version 1.2 was released 7 days ago and is shown as the "latest" release.

https://github.com/Galleondragon/qb64/releases

You probably just need to get rid of the v1.2 tag on what ever that was 7 days ago.

**Comment by FellippeHeitor** [comment]
Though the order of publishing was inverse, the releases do point to the proper commits and are properly ordered when you visualize the releases page, with 1.2 being shown first and marked as Latest release.

Sorry for the confusion.

**Comment by FellippeHeitor** [comment]
![capturar](https://user-images.githubusercontent.com/10699359/36910668-242514fc-1e20-11e8-9431-23e9372cebff.PNG)

**Comment by JasonGlazer** [comment]
Thanks. Just to make sure I understand, the v1.2 release includes everything and more than the v1.1 release?

**Comment by FellippeHeitor** [comment]
Exactly. All updates of version 1.x are incremental so v1.2 includes v1.1 and adds/fixes more.

**Comment by JasonGlazer** [comment]
Great, thank you for that clarification and thank you so much for the tremendous work you have done on QB64. I was a QB45 programmer for many years and appreciate being able to use those skills again and getting some of my old code running.

**Comment by FellippeHeitor** [comment]
Galleon's work is astonishing and I'm a fan as well. It's my pleasure to be part of the team.
