### ISSUE TITLE
Mistype with Parsing GL commands

### ISSUE THREAD

**Issue by AshishKingdom** [Galleondragon/qb64#39]
Hi! There is a critical mistype in `gl2qb_type_convert()` function of opengl_methods.bas
![screenshot_1](https://user-images.githubusercontent.com/21278020/38184610-79234100-3666-11e8-8c31-4ce16a0402ee.png)

It sets "&&" symbol for _OFFSET data type. It must be "%&".

**Comment by FellippeHeitor** [comment]
Good catch.

**Comment by AshishKingdom** [comment]
I fixed this, please see the pull request.
