### ISSUE TITLE
Compilation fails with obscure message if internal/temp/ doesn't exist

### ISSUE THREAD

**Issue by ebourg** [Galleondragon/qb64#45]
When invoking qb64 from the command line to compile a file the following error is returned if the `internal/temp/` directory doesn't exist:

    QB64 COMPILER V1.2
    
    UNEXPECTED INTERNAL COMPILER ERROR!
    Caused by (or after):
    LINE 0:

The reason for the failure isn't obvious. It would be nice to print an explicit message, or even better, automatically create the `internal/temp/` directory.

**Comment by AshishKingdom** [comment]
Which version of QB64 do you have? I've version 1.2 and it compiles the file from command line when internal/temp doesn't exists.

![screenshot_1](https://user-images.githubusercontent.com/21278020/40792526-c75186b8-6517-11e8-9b7d-5d9ade02b21a.png)

**Comment by flukiluke** [comment]
Fixed,
