### ISSUE TITLE
No warning is shown when non-_MEM type variable is used with some _MEM functions

### ISSUE THREAD

**Issue by AshishKingdom** [Galleondragon/qb64#47]
Hi. QB64 doesn't show warning at the status bar when a non-_MEM type variable is used with _MEMNEW and _MEMIMAGE. However, it does with _MEMFREE, _MEMGET and _MEMPUT.

**Comment by AshishKingdom** [comment]
Thanks for fixing it! :)

**Comment by FellippeHeitor** [comment]
Sorry, I did fix it but had to undo the fix, cause it broke something else. This goes back to the list.

**Comment by FellippeHeitor** [comment]
Moved to https://github.com/QB64Team/qb64
