### ISSUE TITLE
Reverse INSTR

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#51]
Searching for things backwards in a string, such as file extensions, path slashes, is very manual. A reverse-INSTR function would be appreciated.

Now this could be its own function, or perhaps you could use a negative value for the START parameter to begin searching backwards, from that point.

**Comment by FellippeHeitor** [comment]
Useful indeed.

**Comment by FellippeHeitor** [comment]
VBScript has InStrRev, so we're likely following that: https://www.w3schools.com/asp/func_instrrev.asp

**Comment by FellippeHeitor** [comment]
Sample usage:

    fullPath$ = "C:\Documents and Settings\Administrator\Desktop\qb64\internal\c\libqb\os\win\libqb_1_2_000000000000.o"
    file$ = MID$(fullPath$, _INSTRREV(fullPath$, "\") + 1)
    PRINT file$

**Comment by Kroc** [comment]
Now I have to rewrite my path code, but at least it'll be shorter! Thanks :)
