### ISSUE TITLE
`_TRIM$` has memory bug!

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#56]
I'm not sure how to narrow this down, but basically _TRIM$ is returning the wrong string! (a previously used one, or perhaps some other memory area)

This code:

```
LET CMD$ = CMD$ + " " + CHR$(34) + FIX_PATH$ + DIR_ENGINE$ + RTRIM$(Engines_Selected.exe) + CHR$(34)
```

Would produce `START /D "saves\gzdoom\DTWID\" "..\..\..\ports\gzdoom-34_x64\gzdoom.exe"` for example, but this code:

```
LET CMD$ = CMD$ + " " + CHR$(34) + FIX_PATH$ + DIR_ENGINE$ + _TRIM$(Engines_Selected.exe) + CHR$(34)
```

(note `_TRIM$` instead of `RTRIM$`) somehow duplicates the string, giving `START /D "saves\gzdoom\DTWID\" "..\..\..\ports\gzdoom-34_x64\START /D "saves\gzdoom\DTWID\" "..\..\..\ports\gzdoom-34_x64\"`!

**Comment by FellippeHeitor** [comment]
The patch contained in 4ad9738b4ddcfe593a9e6849d730e84488f1a758 seems to fix it (but may eventually introduce leaks down the road... that still must be tested). Please try it and let me know if it seems to fix it for your code as well.
