### ISSUE TITLE
Visual glitches and _SCREENMOVE _MIDDLE

### ISSUE THREAD

**Issue by FellippeHeitor** [Galleondragon/qb64#65]
https://www.qb64.org/forum/index.php?topic=489.msg3405#msg3405

**Comment by FellippeHeitor** [comment]
Reproducibility of the issue is an issue, which makes it harder to pinpoint the faulty bit.

**Comment by SteveMcNeill** [comment]
Fix pushed for _SCREENMOVE _MIDDLE issue: 511aee9

**Comment by FellippeHeitor** [comment]
Now about the visual glitches,
