### ISSUE TITLE
Get OpenGL Version?

### ISSUE THREAD

**Issue by Kroc** [Galleondragon/qb64#67]
Is there a means of getting the OpenGL version available on the system? As OpenGL 2.x support is dropped by GZDoom, I'd like to be able to detect the system's OpenGL version and load alternate binaries of configurations as appropriate.

**Comment by AshishKingdom** [comment]
You can use `_glGetString(_GL_VERSION)` to get OpenGL version available on system.

**Comment by FellippeHeitor** [comment]
I'm afraid that's not implemented; a call to a c header with a custom function may be required.

**Comment by FellippeHeitor** [comment]
My bad, I keep forgetting that _GL commands only work inside SUB _GL.

```DIM SHARED glVersion$

DO
    _LIMIT 1
LOOP UNTIL LEN(glVersion$)

PRINT glVersion$

SUB _GL
    glVersion$ = _glGetString(_GL_VERSION)
END SUB```

**Comment by Kroc** [comment]
Compiled as a self-contained example like this, it works, but when added to my program as an include (top and bottom), this locks my program into an infinite loop!

**Comment by Kroc** [comment]
Found the problem -- I've been compiling from command-line and it appears that some IDE-only errors in syntax (use of tabs instead of space) was screwing up compilation.

**Comment by Kroc** [comment]
OK, narrowed an actual bug down -- the sample code given doesn't work with `$SCREENHIDE`

**Comment by FellippeHeitor** [comment]
> Found the problem -- I've been compiling from command-line and it appears that some IDE-only errors in syntax (use of tabs instead of space) was screwing up compilation.

Already fixed in fcf68e093bd647a4b6ee86160c1c6bf2066fac91



> OK, narrowed an actual bug down -- the sample code given doesn't work with `$SCREENHIDE`

$SCREENHIDE prevents the OpenGL context from being created, so it's expected it won't work.

**Comment by Kroc** [comment]
The sample code given is prone to occasional lock-up; is there a different method you can recommend that would continue if no result comes back in 100~300ms or so?

**Comment by FellippeHeitor** [comment]
Try this: 
```
DIM SHARED glVersion$

start! = TIMER
DO
LOOP UNTIL LEN(glVersion$) > 0 OR TIMER - start! > .3

PRINT glVersion$

SUB _GL
    IF LEN(glVersion$) > 0 THEN EXIT SUB
    glVersion$ = _glGetString(_GL_VERSION)
END SUB
```
