### ISSUE TITLE
Improve resolution of paths for DECLARE LIBRARY

### ISSUE THREAD

**Issue by flukiluke** [Galleondragon/qb64#71]
The current logic used is very sucky:
- Code includes must use a .h extension
- Dynamic libraries must begin with lib on Linux
- The appropriate places aren't searched for dynamic libraries, causing machine-specific constants needing to be hard coded in
- Probably other problems

**Comment by FellippeHeitor** [comment]
Moved to https://github.com/QB64Team/qb64
