### ISSUE TITLE
macOS Mojave resize issue

### ISSUE THREAD

**Issue by FellippeHeitor** [Galleondragon/qb64#76]
QB64 and compiled programs are being incorrectly resized in Mojave (beta 2 of 10.14.2 since there is a serious vsync issue with 10.14.0 and 10.14.1 that prevented us from rendering properly) as can be seen on:

https://youtu.be/UEEYaDGZfzE

**Comment by gh0st42** [comment]
Any progress on this issue? Working in the QB64 IDE mostly works as long as you keep the window size or work in fullscreen mode but `SCREEN 13` looks really odd, covering only the lower left of the window and resizing makes everything just worse.

**Comment by FellippeHeitor** [comment]
Nothing found yet.

**Comment by FellippeHeitor** [comment]
It has to do with glViewport() as it's used in internal/c/libqb/gui.cpp and also with the new implementation of free glut in macOS; we have reasons to believe it has to do with high dpi displays (retina displays) and having the texture doubling up in size.

**Comment by FellippeHeitor** [comment]
Help.

**Comment by FellippeHeitor** [comment]
YAY! YAY! Apple fixed the freeglut issue with macOS Mojave 10.14.4!!!
