### ISSUE TITLE
Segmentation Fault after ./setup_lnx.sh

### ISSUE THREAD

**Issue by seisvelas** [Galleondragon/qb64#77]
I installed QB64 and it runs fantastically. But after I closed the window, I saw the words segmentation fault on my console. The exact output is here: https://qb64.org/basbin/7AA5.txt

I have NOT been able to reproduce this phenomenon. After uninstalling and reinstalling, the segfault message does not appear. I just wanted to let you know anyway, since it seems probably...not good. I am running Ubuntu 16.04.5 LTS.

**Comment by FellippeHeitor** [comment]
Thanks for the report.

**Comment by flukiluke** [comment]
QB64 does occasionally segfault on exit and no-one knows why. Given it doesn't affect running of the program I've not been inclined to spend too much time investigating what it probably a threading issue / race condition in shutdown code.
