### ISSUE TITLE
Website crashes or hangs on downloads

### ISSUE THREAD

**Issue by SQLServerIO** [Galleondragon/qb64#78]
I've tried using Chrome 70.0.3538.102 and Firefox 63.0 both only get partial downloads of ether 1.2 or beta 8 of inform.
After the download starts it eventually times out then the website becomes unavailable.
I would recommend moving downloads to github or sourceforge.

**Comment by FellippeHeitor** [comment]
Thanks for reporting.

**Comment by FellippeHeitor** [comment]
@flukiluke thoughts?

**Comment by FellippeHeitor** [comment]
Moved into our "in consideration" folder; not an issue with QB64 itself.
