### ISSUE TITLE
Support for C++11 (or higher) libraries

### ISSUE THREAD

**Issue by AstherixDev** [Galleondragon/qb64#80]
I know this has been already asked as a feature in the forum, but I wanted to leave it here as an official feature request.

C++11 (at least) support would enhance the QB64 language, for example, the support of function objects using the std::function wrapper would allow functions/subs to be placed inside TYPEs. Threading support would be a huge addition to the language. And also the IDE: in low-end computers, it is so slow, it becomes unusable as using it is unpleasant, the only alternative for programming in QB64 in low-end machines is using the command line tool (though compile times are long anyways). Maybe using the regular expression facilities of C++11 (C++17's multiline flag would be even better) can make parsing/realtime error checking faster?

**Comment by callowaysutton** [comment]
C++11 also adds support for more functional operations built-in, so maybe QB64 could add support for Lambda (probably not though haha)

**Comment by FellippeHeitor** [comment]
We have recently upgraded the c++ compiler we ship with QB64. The development build now comes with a very recent version of it you may be interested in checking it out.

**Comment by flukiluke** [comment]
QB64 will not suddenly be rewritten in modern C++, because it is an unholy mess of code fragments being mish-mashed together.
