### ISSUE TITLE
QB64 Linux audio issue and possible fix

### ISSUE THREAD

**Issue by TheOuterLinux** [Galleondragon/qb64#81]
Running the script to install QB64 for Linux produces a lot of chmod related errors but even so, I can still get QB64 to run. However, when trying to play an audio file, doesn't matter what format, I get something like this:

In file included from ../../src/minimp3.c:24:0:
../../src/libc.h:57:36: error: conflicting types for ‘uint64_t’
         typedef unsigned long long uint64_t;
                                    ^~~~~~~~
In file included from /usr/include/stdint.h:37:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9,
                 from ../../src/libc.h:26,
                 from ../../src/minimp3.c:24:
/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h:27:20: note: previous declaration of ‘uint64_t’ was here
 typedef __uint64_t uint64_t;
                    ^~~~~~~~
In file included from ../../src/minimp3.c:24:0:
../../src/libc.h:58:37: error: conflicting types for ‘int64_t’
         typedef   signed long long  int64_t;
                                     ^~~~~~~
In file included from /usr/include/stdint.h:34:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9,
                 from ../../src/libc.h:26,
                 from ../../src/minimp3.c:24:
/usr/include/x86_64-linux-gnu/bits/stdint-intn.h:27:19: note: previous declaration of ‘int64_t’ was here
 typedef __int64_t int64_t;
                   ^~~~~~~
ar: temp/minimp3.o: No such file or directory
g++: error: parts/audio/decode/mp3_mini/os/lnx/src.a: No such file or directory

After looking in the forums, I found somewhat of a solution (https://www.qb64.org/forum/index.php?PHPSESSID=890c711e474b65cf86cca857cbc6ddbb&topic=326.msg2174#msg2174):

...edit the file internal/c/parts/audio/decode/mp3_mini/src/libc.h and make lines 57 and 58 read:

Code: [Select]
typedef __uint64_t uint64_t;
typedef __int64_t int64_t;

However, playing an mp3 results in a quick static sound. Ogg files play just fine though.

**Comment by FellippeHeitor** [comment]
Thanks for the report.

**Comment by TheOuterLinux** [comment]
Oh by the way, I tried a different mp3 file (should have done that sooner), and it played just fine. But, you still have to do the proposed solution to add and play audio without QB64 compile errors.
