### ISSUE TITLE
setup_lnx.sh download links need to be fixed

### ISSUE THREAD

**Issue by TheOuterLinux** [Galleondragon/qb64#82]
The setup_lnx.sh contains links to be used if DOWNLOAD=1. However,:

#Various URL's for downloads
  QB64_URL="http://www.qb64.net/qb64v0978-lnx.tar.gz"
  QB64_SDL_URL="http://www.qb64.net/qb64v0954-lnx.tar.gz"
  QB64_ICON_URL="http://www.qb64.net/qb64icon32.png"

...these links do not exist and need to be fixed.

**Comment by FellippeHeitor** [comment]
DOWNLOAD=1 was used for SDL versions of QB64 prior to 1.000; That section of the script is never really run and the overall installation should work just fine. Did you have problems setting it up? What distro?

**Comment by TheOuterLinux** [comment]
I am using MX Linux 17.1 (Debian), but "lsb_release -si" outputs as "MX." You may be able to use "cat /proc/version" to better grep for "Debian" instead.

Without setting DOWNLOAD=1, I would get a bunch of chmod errors when running the setup_lnx.sh, even though QB64 would run just fine afterwards. But because of the audio related issues I was having when compiling QB64 projects (such as using _SNDPLAYFILE, etc.), I thought trying to set DOWNLOAD=1 and SDL=1 would help bring needed files I might have been missing. However, those links are dead. So, maybe it should either be fixed or removed unless the idea is to use the same script for all Linux QB64 versions.

As of right now, I seem to be able to run/compile and display images and play audio just fine, but it's only "Day 1" of my QB64 usage. I know about the forum, but I thought it was strange how some of the proposed fixes for the audio issue hasn't been dealt with yet, so I reported it here.

**Comment by Dharmesh-sp** [comment]
.bas to be saved to different location (shared drive) instead of in the same folder i.e. C: drive, kindly assist that .bas files should be saved in shared drive by default in windows platform. batch file command would be better.

**Comment by flukiluke** [comment]
The issue here is to remove the download functionality of the setup script as it's not used any more.

**Comment by FellippeHeitor** [comment]
Since it's there but not accessible, I'll consider this a non-issue but rather a matter of a cleanup.
