### ISSUE TITLE
feature request: hide the IDE's title bar

### ISSUE THREAD

**Issue by andymule** [Galleondragon/qb64#86]
Just think of how beautiful that window would be without the windows title bar getting in the way.....

**Comment by FellippeHeitor** [comment]
Assuming you are on Windows, you can already do it like this:

http://www.qb64.org/wiki/Windows_Libraries#Borderless_Window

**Comment by andymule** [comment]
Ah, sorry, i meant for the IDE

**Comment by FellippeHeitor** [comment]
You may enjoy full screen mode. Just hit Alt+ENTER.
