### ISSUE TITLE
Mesa-Loader

### ISSUE THREAD

**Issue by BearzRobotics** [Galleondragon/qb64#87]
OS: Ubuntu Mate 18.04 LTS

I went to build this and it compiled fine, but when I tried to run it, this popped up in the terminal. I haven't had a problem with other apps (steam games).

libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  52
  Current serial number in output stream:  51

**Comment by chronokitsune3233** [comment]
Just a guess, but I believe you need to install the [`mesa-va-drivers`](https://packages.ubuntu.com/bionic/mesa-va-drivers) package, which contains the `radeonsi` video driver. The other important package here would be [`libgl1-mesa-dri`](https://packages.ubuntu.com/bionic/libgl1-mesa-dri), which contains both the `radeonsi` and `swrast` DRI modules. Hopefully that makes things work, or at least results in a different error message.

**Comment by BearzRobotics** [comment]
Both packages were already installed.  

dakota@pop-os:~/bin/qb64$ sudo apt install mesa-va-drivers libgl1-mesa-dri
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgl1-mesa-dri is already the newest version (19.0~git1901261930.41ddf1~oibaf~c).
libgl1-mesa-dri set to manually installed.
mesa-va-drivers is already the newest version (19.0~git1901261930.41ddf1~oibaf~c).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

**Comment by callowaysutton** [comment]
You're running 64 bit right?

**Comment by callowaysutton** [comment]
Try uninstalling llvm if it's installed and then running this command
```
apt-cache policy libgl1-mesa-dri libgl1-mesa-dri:i386 | grep -C1 Installed
```

**Comment by BearzRobotics** [comment]
So I just apt removed llvm and ran your command.

Output: 
dakota@pop-os:~/bin/qb64$ apt-cache policy libgl1-mesa-dri libgl1-mesa-dri:i386 | grep -C1 Installed
libgl1-mesa-dri:
  Installed: 19.0~git1901290730.932ed9~oibaf~c
  Candidate: 19.0~git1901290730.932ed9~oibaf~c
--
libgl1-mesa-dri:i386:
  Installed: 19.0~git1901290730.932ed9~oibaf~c
  Candidate: 19.0~git1901290730.932ed9~oibaf~c

I'm still getting the same problem.

**Comment by callowaysutton** [comment]
Hmm all of your libs are up to date and everything?
Make sure you have all of these libraries btw
```
g++ mesa-common-dev libglu1-mesa-dev libasound2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev
```

**Comment by BearzRobotics** [comment]
Sorry for the late reply. after apt install your list of packages everythings working now.

**Comment by callowaysutton** [comment]
Alright good, I think this issue is closed now
