### ISSUE TITLE
Separating the IDE and Compiler?

### ISSUE THREAD

**Issue by callowaysutton** [Galleondragon/qb64#88]
Is there any thought on separating the IDE and the Compiler?
It seems like it would make the compiler more portable, especially to other IDE's and plus make the QB64 IDE portable for other languages as well.

This isn't an issue or anything I'm just curious

**Comment by FellippeHeitor** [comment]
The IDE is comprised of two includes. One at the top of qb64.bas (ide_global.bas) and on at the bottom (ide_methods.bas). Just removing those two lines and recompiling qb64.bas will give you an IDE-free compiler. The other way around though wouldn't be as simple, as the IDE heavily relies on being a module of the main program.
