### ISSUE TITLE
CLS doesn't clear console text

### ISSUE THREAD

**Issue by callowaysutton** [Galleondragon/qb64#90]

**Comment by FellippeHeitor** [comment]
@callowaysutton your changes began causing our auto builds to stop working. Here's the full error log which may help in finding the culprit bits: https://ci.appveyor.com/project/flukiluke/qb64/builds/23493105/job/5o56jmumtytlka7b

**Comment by FellippeHeitor** [comment]
@callowaysutton sorry... referenced you but you opened the issue, not the pull request.

@chronokitsune3233: your changes began causing our auto builds to stop working. Here's the full error log which may help in finding the culprit bits: https://ci.appveyor.com/project/flukiluke/qb64/builds/23493105/job/5o56jmumtytlka7b

**Comment by paulwratt** [comment]
Why was the initial commit accepted as is? It wrongiy(?) chopped a piece of Windows CLS code out too.

It appears from the commit that the target platform (Linux or OSX) was not using NCurses.  is ther a situation where this is a normal way to write QB64 programs? If so, then there should should be a make switch option added (as opposed to wholesale code deletion).

What is the issues with the "ncurses conflict" mentioned in the code? The code uses `tput clear` which is the correct (and clean) way to clear the console/terminal.

**Comment by FellippeHeitor** [comment]
@SteveMcNeill do the new functions you added cover this issue?

**Comment by SteveMcNeill** [comment]
They do, but for Windows only.  I don’t have a Linux/Mac machine to test things on, so the only changes I could make were to the windows console.  Linux terminal still remains the same.
