### ISSUE TITLE
1.3 should include the updated help files

### ISSUE THREAD

**Issue by brabbin** [Galleondragon/qb64#94]
Because of the wiki formatting change, the internal help files are corrupted in 1.3. You can fix it by updating all the pages in the IDE, but it'd be nice if they were included.

![corrupt](https://user-images.githubusercontent.com/32730879/56077800-57c91780-5dae-11e9-8775-d763aae2a762.png)

**Comment by FellippeHeitor** [comment]
It does now. https://github.com/Galleondragon/qb64/tree/v1.3

**Comment by brabbin** [comment]
Thanks!
