### ISSUE TITLE
Binary Format: "Error Launching Conversion Utility"

### ISSUE THREAD

**Issue by donatj** [Galleondragon/qb64#95]
I am on QB64 1.3 on OS X

I have hundreds of old programs I wrote in the 90s that are saved in the binary format. I would **love** to be able to read them.  Whenever I try though I am presented with this error.

Is this something I can correct? Is it a bug? I'd love any help I could get here.

![image](https://user-images.githubusercontent.com/133747/56762033-7b07a580-6764-11e9-89c4-262afd098984.png)

![image](https://user-images.githubusercontent.com/133747/56762049-85c23a80-6764-11e9-8686-779ada4d2033.png)

**Comment by FellippeHeitor** [comment]
I tried it on my machine just now (Mojave, 10.14.4) and it worked:
![Captura de Tela 2019-04-25 às 23 19 42](https://user-images.githubusercontent.com/10699359/56779298-bdef6a80-67b0-11e9-9f3b-db0aaf3685a5.png)
![Captura de Tela 2019-04-25 às 23 19 57](https://user-images.githubusercontent.com/10699359/56779304-c6e03c00-67b0-11e9-9568-f07eb2f90411.png)

Would you mind launching QB64 from terminal and telling me what it shows when you try to load a 4.5 binary format file? Look at what mine shows in the screenshot above for reference.

What QB64 does internally the first time a binary .BAS file is loaded is compile the conversion utility in source/utilities/QB45BIN.bas into internal/utilities/QB45BIN - that's the binary that you should have after a conversion is triggered.

**Comment by j-h-a** [comment]
Had the same issue, here's how to solve:

1. Run qb64 and open `source/QB45BIN.bas`
2. Press F11 (or go to menu: `Run`>`Make Executable Only`)
3. Move `QB45BIN` executable (in root qb64 directory) to `internal/utilities/QB45BIN`
4. Now when you open your file it will find the tool and work.

**Comment by donatj** [comment]
Excellent. I will try that out on Monday when I'm home from my trip.

**Comment by FellippeHeitor** [comment]
@j-h-a QB64 should have been able to compile the utility on its own. Any error messages popping up on terminal?

**Comment by donatj** [comment]
@j-h-a THANK YOU. That fixed it!
