### ISSUE TITLE
Allow definable keyword prefix

### ISSUE THREAD

**Issue by youreperfect** [Galleondragon/qb64#97]
This is a feature request, the current version is 1.3

I would like to have a keyword slash magic variable similar to:
```QB_KEYWORD_PREFIX```

setting this magic variable to a string would change the way the new keywords added in QB64 are named.

So currently you have:
```PRINT _AXIS(a)```

With this feature you could have:
```
QB_KEYWORD_PREFIX = ""
PRINT AXIS(a)
```
or
```
QB_KEYWORD_PREFIX = "QB64_"
PRINT QB64_AXIS(a)
```

The first example could be a way for people who don't like the underscores to remove them.
The second example could be used by larger projects that may use leading underscore naming in their own code (ie for pseudo-private functions and variables) or large projects where keeping track where a function or variable is defined is useful.

I presume the convention would be to define this at the top of the script (though I'm not sure if that sould be compiler-enforced).

**Comment by youreperfect** [comment]
After thinking about it some more I think its ok to close this as "wontfix" personally.

**Comment by FellippeHeitor** [comment]
Let's just let it sink a bit more :-)

**Comment by FellippeHeitor** [comment]
Moved to https://github.com/QB64Team/qb64
