### ISSUE TITLE
Support variables named 💩 (Unicode support)

### ISSUE THREAD

**Issue by youreperfect** [Galleondragon/qb64#98]
Feature request - current version is 1.3

![image](https://user-images.githubusercontent.com/49788602/60056479-ab0cef80-96a6-11e9-
88cd-a82d0833b176.png)

Pasting 💩 into the editor results in two ```??``` which is not a valid variable name.

**Comment by youreperfect** [comment]
Related talk about poop emoji in C++
https://www.kdab.com/unexpected-c-journey/

**Comment by FellippeHeitor** [comment]
Support to unicode is a long awaited feature even for regular text, not just emoji. We currently only support the ASCII set.

**Comment by ProxyPlayerHD** [comment]
>Support to unicode is a long awaited feature even for regular text, not just emoji. We currently only support the ASCII set.

that explains why i cannot comment my code in my natice languge (no support for öäüß) or use the "degree" symbol(°).

**Comment by FellippeHeitor** [comment]
> > Support to unicode is a long awaited feature even for regular text, not just emoji. We currently only support the ASCII set.
> 
> that explains why i cannot comment my code in my natice languge (no support for öäüß) or use the "degree" symbol(°).

Yeah, sorry about that for now.

**Comment by FellippeHeitor** [comment]
Closing as it will require a full rewrite of key parts or even a switch to another library completely, which won't be done before v2
