### ISSUE TITLE
Some GL Menu Spam + Spam Open Program

### ISSUE THREAD

**Issue by PmasVterP** [Galleondragon/qb64#99]
I don't know how, but all of a sudden, when I started to run a program, my computer lagged and spammed boxes with something about "GL" version or something and the program I made was being spammed open. I had to force shutdown my computer. I did run my programs before and there wasn't any bugs, but then this happened. I tried rerunning the code again after this and it worked perfectly well.

**Comment by PmasVterP** [comment]
![Screenshot (132)](https://user-images.githubusercontent.com/26689496/60218508-931ba400-983d-11e9-859d-3622a9b09cb0.png)
QB64 and File Explorer were the only programs on (and background usage).

**Comment by FellippeHeitor** [comment]
Can you try to reproduce the issue and share a screenshot?

**Comment by PmasVterP** [comment]
I guess I can try to crash my computer again. I don't know how it happened, but I'll try anyways.

**Comment by PmasVterP** [comment]
I kind of tried it again. I found out if you spam F5, then your (or at least my) computer lagged and had the program open and another thing that says "Missing GL Version". Closing the original program of the popup closes the program. I'll share a screenshot, except it will be less than what happened, because it kept spamming the 2 programs constantly with I think I only clicked F5 one or two times.

**Comment by PmasVterP** [comment]
I almost killed my computer doing this. QB64.exe became non-responsive. 
![Image](https://user-images.githubusercontent.com/26689496/60401444-9a99c080-9b4f-11e9-81a1-37548055e233.png)

**Comment by FellippeHeitor** [comment]
``` I found out if you spam F5, then your (or at least my) computer lagged and had the program open and another thing that says "Missing GL Version".```

You’re launching a compiled program multiple times by “spamming” the F5 key, which I assume means hitting it too often instead of just once as intended.

The fix is, don’t “spam” it.

**Comment by PmasVterP** [comment]
But, I'm wondering how it happened the first time... I didn't spam (or I at least remember it like that).

**Comment by FellippeHeitor** [comment]
Likely a memory issue, due to too many instances open and not able to link to OpenGL at runtime, I don’t know.
